---
server:
  port: 8020

# 数据库数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles: dev
#  应用名称 （nacos会将该名称当作服务名称）
  application:
    name: user-service
#    不配也行，有默认值
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
#        命名空间，用来隔离不同的服务实例 e.g.开发环境，测试环境， 默认值是public
        namespace: public
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    timeout: 5000


mybatis:
  type-aliases-package: com.example.springbootmybatis.pojo # 别名
  mapper-locations: classpath:/mybatis/*.xml # xml文件

logging:
  file:
    name: log/log.log
  level:
    root: info
    com.example.springbootmybatis: debug
---
spring:
  profiles:
    active: dev
